### PR TITLE
Add italian language

### PR DESCRIPTION
**Pull request by bovirus**

### CODE REVIEW

**Comment by bovirus** [comment]
@emoacht 

Please check and merge.

**Comment by emoacht** [comment]
Thanks for the PR.
I am just wondering the following translations could lose the implication of the original wording. Could you think about more suitable wording?

Rush=Scansione
"rush" in this app does not mean just "scan" but hurry up or press or spur the OS to scan Wi-Fi networks in shorter intervals.

Engage=Connessione
"engage" in this app does not mean just "connect" but intervene or enter into or take part in the process of the priorities of connections to Wi-Fi networks.

**Comment by emoacht** [comment]
No response for four months. It's time to close this PR.

**Comment by bovirus** [comment]
@emoacht

I hope you merge my changes.

"Rush" didn't have a familiar translation in italian.
The term that is more similar is "Scansione".

**Pull request closed without merging**
